=== CommonRoad/opentrafficsim/ots-demo/src/main/resources/xsd/ots-definitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentrafficsim.org/ots"
  xmlns:ots="http://www.opentrafficsim.org/ots" 
  xmlns:xi="http://www.w3.org/2001/XInclude"
  elementFormDefault="qualified">

  <!-- http://www.w3.org/2009/01/xml.xsd -->
  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="ref/xml.xsd" />
  <!-- http://www.w3.org/2001/xinclude.xsd -->
  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="ref/xinclude.xsd" />

  <xsd:include schemaLocation="ots-types.xsd" />

  <!-- ================================================================================================== -->
  <!-- =============================================== ELEMENTS ========================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="GTUTYPE">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="PARENT" type="xsd:string" use="optional" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:GTUTYPE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTEMPLATE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="LENGTHDIST" type="ots:LENGTHDISTTYPE" minOccurs="1" />
        <xsd:element name="WIDTHDIST" type="ots:LENGTHDISTTYPE" minOccurs="1" />
        <xsd:element name="MAXSPEEDDIST" type="ots:SPEEDDISTTYPE" minOccurs="1" />
        <xsd:element name="MAXACCELERATIONDIST" type="ots:ACCELERATIONDISTTYPE" minOccurs="0" />
        <xsd:element name="MAXDECELERATIONDIST" type="ots:ACCELERATIONDISTTYPE" minOccurs="0" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTEMPLATES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:GTUTEMPLATE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="COMPATIBILITY">
    <xsd:complexType>
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="DIRECTION" type="ots:DRIVINGDIRECTIONTYPE" use="required">
        <xsd:annotation>
          <xsd:documentation source="description">
            DRIVINGDIRECTIONTYPE: FORWARD|BACKWARD|BOTH|NONE
          </xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LANETYPE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:COMPATIBILITY" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="PARENT" type="xsd:string" use="optional" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LANETYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:LANETYPE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINKTYPE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:COMPATIBILITY" minOccurs="1" maxOccurs="unbounded" />
        <xsd:element ref="ots:SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="PARENT" type="xsd:string" use="optional" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINKTYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:LINKTYPE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SPEEDLIMIT">
    <xsd:complexType>
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="LEGALSPEEDLIMIT" type="ots:SPEEDTYPE" use="optional" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="CROSSSECTIONELEMENT">
    <xsd:sequence>
      <xsd:choice minOccurs="0">
        <xsd:element name="CENTEROFFSET" type="ots:LENGTHTYPE" />
        <xsd:element name="LEFTOFFSET" type="ots:LENGTHTYPE" />
        <xsd:element name="RIGHTOFFSET" type="ots:LENGTHTYPE" />
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETSTART" type="ots:LENGTHTYPE" />
            <xsd:element name="LEFTOFFSETSTART" type="ots:LENGTHTYPE" />
            <xsd:element name="RIGHTOFFSETSTART" type="ots:LENGTHTYPE" />
          </xsd:choice>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETEND" type="ots:LENGTHTYPE" />
            <xsd:element name="LEFTOFFSETEND" type="ots:LENGTHTYPE" />
            <xsd:element name="RIGHTOFFSETEND" type="ots:LENGTHTYPE" />
          </xsd:choice>
        </xsd:sequence>
      </xsd:choice>
      <xsd:choice>
        <xsd:element name="WIDTH" type="ots:POSITIVELENGTHTYPE" />
        <xsd:sequence>
          <xsd:element name="WIDTHSTART" type="ots:LENGTHTYPE" />
          <xsd:element name="WIDTHEND" type="ots:LENGTHTYPE" />
        </xsd:sequence>
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="CSELANE">
    <xsd:complexContent>
      <xsd:extension base="ots:CROSSSECTIONELEMENT">
        <xsd:sequence>
          <xsd:element ref="ots:SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="ID" type="xsd:string" use="required" />
        <xsd:attribute name="LANETYPE" type="xsd:string" use="required" />
        <xsd:attribute name="DESIGNDIRECTION" type="xsd:boolean" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="CSENOTRAFFICLANE">
    <xsd:complexContent>
      <xsd:extension base="ots:CROSSSECTIONELEMENT">
        <xsd:attribute name="ID" type="xsd:string" use="optional" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="CSESHOULDER">
    <xsd:complexContent>
      <xsd:extension base="ots:CROSSSECTIONELEMENT">
        <xsd:attribute name="ID" type="xsd:string" use="optional" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="CSESTRIPE">
    <xsd:sequence>
      <xsd:choice minOccurs="0">
        <xsd:element name="CENTEROFFSET" type="ots:LENGTHTYPE" />
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETSTART" type="ots:LENGTHTYPE" />
          </xsd:choice>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETEND" type="ots:LENGTHTYPE" />
          </xsd:choice>
        </xsd:sequence>
      </xsd:choice>
      <xsd:element name="DRAWINGWIDTH" type="ots:POSITIVELENGTHTYPE" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="ID" type="xsd:string" use="optional" />
    <xsd:attribute name="TYPE" type="ots:STRIPETYPE" use="required" />
  </xsd:complexType>

  <xsd:element name="ROADLAYOUTS">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ots:ROADLAYOUT" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="BASICROADLAYOUT">
    <xsd:sequence>
      <xsd:sequence minOccurs="1" maxOccurs="unbounded">
        <xsd:choice>
          <xsd:element name="LANE" type="ots:CSELANE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="NOTRAFFICLANE" type="ots:CSENOTRAFFICLANE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="SHOULDER" type="ots:CSESHOULDER" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="STRIPE" type="ots:CSESTRIPE" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:element ref="ots:SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="LANEKEEPING" type="ots:LANEKEEPINGTYPE" use="optional" />
    <xsd:attribute ref="xml:base" />
  </xsd:complexType>

  <xsd:element name="ROADLAYOUT">
    <xsd:annotation>
      <xsd:documentation source="description">
        Road layout. Lanes to the right of the design line have negative
        offset. Those to the right have positive offset. When not specifying offsets, sequence
        the lines from right (most negative) to left (most positive).
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:extension base="ots:BASICROADLAYOUT">
          <xsd:attribute name="ID" type="xsd:string" use="required" />
          <xsd:attribute name="LINKTYPE" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>
    <!-- the LANE.ID should be unique within one ROADLAYOUT -->
    <xsd:unique name="uniqueRoadLayoutLaneId">
      <xsd:selector xpath="ots:LANE" />
      <xsd:field xpath="@ID" />
    </xsd:unique>
  </xsd:element>

  <xsd:element name="PARAMETERTYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element name="STRING" type="ots:PARAMETERTYPESTRING" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="ACCELERATION" type="ots:PARAMETERTYPEACCELERATION" minOccurs="0"
            maxOccurs="unbounded" />
          <xsd:element name="BOOLEAN" type="ots:PARAMETERTYPEBOOLEAN" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="CLASS" type="ots:PARAMETERTYPECLASS" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="DOUBLE" type="ots:PARAMETERTYPEDOUBLE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="FLOAT" type="ots:PARAMETERTYPEFLOAT" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="LONG" type="ots:PARAMETERTYPELONG" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="DURATION" type="ots:PARAMETERTYPEDURATION" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="FRACTION" type="ots:PARAMETERTYPEFRACTION" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="FREQUENCY" type="ots:PARAMETERTYPEFREQUENCY" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="INTEGER" type="ots:PARAMETERTYPEINTEGER" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="LENGTH" type="ots:PARAMETERTYPELENGTH" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element name="LINEARDENSITY" type="ots:PARAMETERTYPELINEARDENSITY" minOccurs="0"
            maxOccurs="unbounded" />
          <xsd:element name="SPEED" type="ots:PARAMETERTYPESPEED" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- ================================================================================================== -->
  <!-- ============================================== DEFINITIONS ======================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="DEFINITIONS">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="xi:include" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ots:GTUTYPES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ots:GTUTEMPLATES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ots:LINKTYPES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ots:LANETYPES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ots:ROADLAYOUTS" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ots:PARAMETERTYPES" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== CommonRoad/opentrafficsim/ots-demo/src/main/resources/xsd/defaults/default_gtutypes.xml
<ots:GTUTYPES xmlns:ots="http://www.opentrafficsim.org/ots" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.opentrafficsim.org/ots ../ots-definitions.xsd">

<!--
        ROAD_USER = new GTUType("ROAD_USER", null);
        WATERWAY_USER = new GTUType("WATERWAY_USER", null);
        RAILWAY_USER = new GTUType("RAILWAY_USER", null);

        SHIP = new GTUType("SHIP", WATERWAY_USER);
        TRAIN = new GTUType("TRAIN", RAILWAY_USER);
        PEDESTRIAN = new GTUType("PEDESTRIAN", ROAD_USER);
        BICYCLE = new GTUType("BICYCLE", ROAD_USER);
        MOPED = new GTUType("MOPED", BICYCLE);

        VEHICLE = new GTUType("VEHICLE", ROAD_USER);
        EMERGENCY_VEHICLE = new GTUType("EMERGENCY_VEHICLE", VEHICLE);
        CAR = new GTUType("CAR", VEHICLE);
        VAN = new GTUType("VAN", VEHICLE);
        BUS = new GTUType("BUS", VEHICLE);
        TRUCK = new GTUType("TRUCK", VEHICLE);
        SCHEDULED_BUS = new GTUType("SCHEDULED BUS", BUS); 
 -->

	<ots:GTUTYPE ID="NONE" DEFAULT="true" />

	<ots:GTUTYPE ID="ROAD_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="WATERWAY_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="RAILWAY_USER" DEFAULT="true" />

	<ots:GTUTYPE ID="SHIP" PARENT="WATERWAY_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="TRAIN" PARENT="RAILWAY_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="PEDESTRIAN" PARENT="ROAD_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="BICYCLE" PARENT="ROAD_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="MOPED" PARENT="BICYCLE" DEFAULT="true" />

	<ots:GTUTYPE ID="VEHICLE" PARENT="ROAD_USER" DEFAULT="true" />
	<ots:GTUTYPE ID="EMERGENCY_VEHICLE" PARENT="VEHICLE" DEFAULT="true" />
	<ots:GTUTYPE ID="CAR" PARENT="VEHICLE" DEFAULT="true" />
	<ots:GTUTYPE ID="VAN" PARENT="VEHICLE" DEFAULT="true" />
	<ots:GTUTYPE ID="BUS" PARENT="VEHICLE" DEFAULT="true" />
	<ots:GTUTYPE ID="TRUCK" PARENT="VEHICLE" DEFAULT="true" />
	<ots:GTUTYPE ID="SCHEDULED_BUS" PARENT="BUS" DEFAULT="true" />

</ots:GTUTYPES>

=== CommonRoad/opentrafficsim/ots-demo/src/main/resources/xsd/defaults/default_lanetypes.xml
<ots:LANETYPES xmlns:ots="http://www.opentrafficsim.org/ots" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots ../ots-definitions.xsd">

<!--
        GTUCompatibility<LaneType> noTrafficCompatibility = new GTUCompatibility<>((LaneType) null);
        NONE = new LaneType("NONE", null, noTrafficCompatibility);
        GTUCompatibility<LaneType> roadCompatibility = new GTUCompatibility<>((LaneType) null);
        roadCompatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_BOTH);
        TWO_WAY_LANE = new LaneType("TWO_WAY_LANE", null, roadCompatibility);
        RURAL_ROAD_LANE = new LaneType("RURAL_ROAD", TWO_WAY_LANE, new GTUCompatibility<>(roadCompatibility));
        URBAN_ROAD_LANE = new LaneType("URBAN_ROAD", TWO_WAY_LANE, new GTUCompatibility<>(roadCompatibility));
        RESIDENTIAL_ROAD_LANE = new LaneType("RESIDENTIAL_ROAD", TWO_WAY_LANE, new GTUCompatibility<>(roadCompatibility));
        GTUCompatibility<LaneType> oneWayLaneCompatibility = new GTUCompatibility<>(roadCompatibility);
        oneWayLaneCompatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_PLUS);
        oneWayLaneCompatibility.addAllowedGTUType(GTUType.PEDESTRIAN, LongitudinalDirectionality.DIR_BOTH);
        ONE_WAY_LANE = new LaneType("ONE_WAY_LANE", oneWayLaneCompatibility);
        GTUCompatibility<LaneType> highwayLaneCompatibility = new GTUCompatibility<>(oneWayLaneCompatibility)
                .addAllowedGTUType(GTUType.PEDESTRIAN, LongitudinalDirectionality.DIR_NONE);
        FREEWAY = new LaneType("FREEWAY", highwayLaneCompatibility);
        HIGHWAY = new LaneType("HIGHWAY", highwayLaneCompatibility);
        GTUCompatibility<LaneType> busLaneCompatibility = new GTUCompatibility<>(roadCompatibility);
        busLaneCompatibility.addAllowedGTUType(GTUType.BUS, LongitudinalDirectionality.DIR_BOTH);
        busLaneCompatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_NONE);
        BUS_LANE = new LaneType("BUS_LANE", busLaneCompatibility);
        GTUCompatibility<LaneType> mopedAndBicycleLaneCompatibility = new GTUCompatibility<>(roadCompatibility);
        mopedAndBicycleLaneCompatibility.addAllowedGTUType(GTUType.BICYCLE, LongitudinalDirectionality.DIR_BOTH);
        mopedAndBicycleLaneCompatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_NONE);
        MOPED_PATH = new LaneType("MOPED_PATH", mopedAndBicycleLaneCompatibility);
        GTUCompatibility<LaneType> bicycleOnlyCompatibility = new GTUCompatibility<>(mopedAndBicycleLaneCompatibility);
        bicycleOnlyCompatibility.addAllowedGTUType(GTUType.MOPED, LongitudinalDirectionality.DIR_NONE);
        BICYCLE_PATH = new LaneType("BICYCLE_PATH", bicycleOnlyCompatibility);
        GTUCompatibility<LaneType> pedestriansOnly = new GTUCompatibility<>(roadCompatibility);
        pedestriansOnly.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_NONE);
        FOOTPATH = new LaneType("FOOTPATH", pedestriansOnly);
 -->

  <ots:LANETYPE ID="NONE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="NONE" DIRECTION="NONE"/>
  </ots:LANETYPE>
  
  <ots:LANETYPE ID="TWO_WAY_LANE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="RURAL_ROAD" PARENT="TWO_WAY_LANE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="URBAN_ROAD" PARENT="TWO_WAY_LANE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="RESIDENTIAL_ROAD" PARENT="TWO_WAY_LANE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="ONE_WAY_LANE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="PEDESTRIAN" DIRECTION="BOTH" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="FREEWAY" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="PEDESTRIAN" DIRECTION="NONE" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="HIGHWAY" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="PEDESTRIAN" DIRECTION="NONE" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="BUS_LANE" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="NONE" />
    <ots:COMPATIBILITY GTUTYPE="BUS" DIRECTION="FORWARD" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="MOPED_PATH" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="NONE" />
    <ots:COMPATIBILITY GTUTYPE="BICYCLE" DIRECTION="FORWARD" />
    <!-- a MOPED is a special BICYCLE -->
  </ots:LANETYPE>

  <ots:LANETYPE ID="BICYCLE_PATH" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="NONE" />
    <ots:COMPATIBILITY GTUTYPE="BICYCLE" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="MOPED" DIRECTION="NONE" />
  </ots:LANETYPE>

  <ots:LANETYPE ID="FOOTPATH" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="NONE" />
    <ots:COMPATIBILITY GTUTYPE="PEDESTRIAN" DIRECTION="BOTH" />
  </ots:LANETYPE>

</ots:LANETYPES>
